[package]
name = "parsers"
version = "0.5.0"
license = "BSD-3-Clause-Clear"
edition = "2024"

[dependencies]
ra2m_sim = {version= "1.0.0", path="../../ra2m_sim"}

bincode = "1.3.3"
getset = "0.1.2" # Ease getter/setter generation
polars = { version = "0.44", features = ["lazy", "parquet", "json", "dtype-struct"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"

strum = "0.26"
strum_macros = "0.26"


tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
default = []
