[package]
name = "ra2m_sim_containers"
description = "Ra2m dedicated containers."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rustix = {version = "0.38", features = ["mm"]}
anyhow = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
