//! Let Hw process to wait on inter- process/ modules event
//! Used a global event store to convert between event user name and event uid.
//!

use super::*;
use ra2m_sim_output::log::{Category, Verbosity};
use ra2m_sim_output::{default_catverb, log, log_format, Output};

use once_cell::sync::OnceCell;
use std::{
    collections::HashMap,
    future::Future,
    io::Write, // use by log macro
    pin::Pin,
    sync::atomic::{AtomicUsize, Ordering},
    sync::Mutex,
    task::{Context, Poll},
};

/// Event structure that enable an async function to wait for a given event that will occurred in
/// the future (generated by another HwThread).
#[derive(Debug)]
pub struct Event {
    uid: usize,
    order_pushed: bool,
}

impl Event {
    pub fn wait(name: &str) -> Self {
        let uid = EventKeeper::event_uid(name);
        Event {
            uid,
            order_pushed: false,
        }
    }

    pub fn triggered(name: &str, at: Option<time::Tick>) -> usize {
        let at = if let Some(tick) = at {
            tick
        } else {
            cur_tick()
        };
        let uid = EventKeeper::event_uid(name);
        let order = scheduler::Order::NotifyAt(at, uid);
        scheduler::SchedulerAPI::push_order(order);
        uid
    }
}

impl Future for Event {
    type Output = ();

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
        // Ready path
        let task_id = cx.waker().data() as usize;
        if EventKeeper::is_triggered(self.uid, task_id) {
            Poll::Ready(())
        } else {
            // Register wait on event in the scheduler
            if !self.order_pushed {
                // Prevent deadlock on unneeded poll
                let order = scheduler::Order::WaitOn(self.uid, cx.waker().clone());
                scheduler::SchedulerAPI::push_order(order);
                self.order_pushed = true;
            }
            Poll::Pending
        }
    }
}

/// Enable user to easily lookup/ register for events and see currently fired events
/// Let a one to one matching between event name and event uid and also keep track of the currently
/// triggered events
pub struct EventKeeper {
    /// Atomic counter to retrieved the next event uid
    nxt_event_uid: AtomicUsize,
    /// Event store that hash event_name with event_uid
    name_uid: Mutex<HashMap<String, usize>>,

    /// List of fired event in the current delta-cycle
    /// Need to be iterated and thus couldn't use Array/Seg Queue
    triggered_events: Mutex<Vec<usize>>,

    /// List of woken process in the current delta-cycle, use to prevent spinlock on event to
    /// lock the async scheduler. A process could be woken only once per delta-cycle.
    /// Use Vec instead of ArrayQueue/SegQueue for use of clear method
    woken_process: Mutex<Vec<usize>>,
}

impl EventKeeper {
    /// Utility function to register/lookup for event name
    pub fn event_uid(name: &str) -> usize {
        let ek = EVENT_KEEPER.get_or_init(|| EventKeeper {
            nxt_event_uid: AtomicUsize::new(0),
            name_uid: Mutex::new(HashMap::new()),
            triggered_events: Mutex::new(Vec::new()),
            woken_process: Mutex::new(Vec::new()),
        });
        let mut name_uid = ek.name_uid.lock().unwrap();
        if name_uid.contains_key(name) {
            name_uid[name]
        } else {
            let uid = ek.nxt_event_uid.fetch_add(1, Ordering::SeqCst);
            name_uid.insert(name.to_owned(), uid);
            log!(Category::Scheduler, Verbosity::Debug => name, uid => "New event registered");
            uid
        }
    }

    /// Utility function to clear the currently fired events
    /// This should be done on simulation time advance (eg new delta-cycle)
    pub fn clear_triggered_events() {
        if let Some(event_keeper) = EVENT_KEEPER.get() {
            let mut triggered_events = event_keeper.triggered_events.lock().unwrap();
            triggered_events.clear();
            let mut woken_process = event_keeper.woken_process.lock().unwrap();
            woken_process.clear();
        }
    }

    pub fn trigger_event(event_uid: usize) {
        if let Some(event_keeper) = EVENT_KEEPER.get() {
            let mut triggered_events = event_keeper.triggered_events.lock().unwrap();
            triggered_events.push(event_uid);
        } else {
            panic!("Ask to trigger Event [uid: {event_uid}] but none EventKeeper registered");
        }
    }

    pub fn is_triggered(event_uid: usize, task_id: usize) -> bool {
        if let Some(event_keeper) = EVENT_KEEPER.get() {
            let triggered_events = event_keeper.triggered_events.lock().unwrap();
            if triggered_events.contains(&event_uid) {
                let mut woken_process = event_keeper.woken_process.lock().unwrap();
                if !woken_process.contains(&task_id) {
                    // associated process not already woken-up
                    woken_process.push(task_id);
                    return true;
                }
            }
        }
        false
    }

    /// Utility function to retrieved name from event uid
    /// i.e. reverse lookup
    /// Used for debug purpose
    pub fn event_name(uid: usize) -> String {
        let ek = EVENT_KEEPER.get_or_init(|| EventKeeper {
            nxt_event_uid: AtomicUsize::new(0),
            name_uid: Mutex::new(HashMap::new()),
            triggered_events: Mutex::new(Vec::new()),
            woken_process: Mutex::new(Vec::new()),
        });
        let name_uid = ek.name_uid.lock().unwrap();
        for (key, val) in name_uid.iter() {
            if *val == uid {
                return key.to_string();
            }
        }
        "Unknown_evt".to_string()
    }
}

/// Utility macro to create coherent event naming in the simulation hierarchy
#[macro_export]
macro_rules! forge_event_name {
    ($module_path: expr, $event_name: expr) => {
        format!("{}::{}", $module_path, $event_name)
    };

    (|$self: ident| $event_name: expr ) => {{
        forge_event_name!($self.properties().path(), $event_name)
    }};
}

/// Event store is backed by a global variable wrapped in once_cell
pub static EVENT_KEEPER: OnceCell<EventKeeper> = OnceCell::new();

#[cfg(test)]
mod units_tests {
    use super::*;
    use crate::unit::TimeUnit;

    use serial_test::serial;

    // Utility functions
    async fn prc_wait_on_event(
        tid: usize,
        name: &str,
        log_sender: crossbeam::channel::Sender<(usize, time::Tick)>,
    ) {
        for i in 0.. {
            let name = format!("{name}_{i}");
            event::Event::wait(&name).await;
            println!(
                "{}: prc_wait_on_event {}::{} fired",
                time::TimeKeeper::cur_tick(),
                tid,
                name
            );
            log_sender
                .send((tid, time::TimeKeeper::cur_tick()))
                .unwrap();
        }
        scheduler::SchedulerAPI::unregister_prc();
    }

    async fn trigger_events(name: &str, delay: time::Tick, nb_iter: usize) {
        let mut acc = time::TimeKeeper::cur_tick();
        for i in 0..nb_iter {
            let name = format!("{name}_{i}");
            acc += delay;
            event::Event::triggered(&name, Some(acc));
            println!(
                "{}: registered event {}::{}",
                time::TimeKeeper::cur_tick(),
                name,
                acc
            );
        }
    }

    #[tokio::test]
    #[serial]
    async fn test_event() {
        // Create global simulation state and custom scheduler for hardware task
        let mut sched = init_simulation(0, 1.ps(), time::TimingMode::LT, DFLT_HW_PROCESS);
        let (log_s, log_r) = crossbeam::channel::unbounded();

        // Spawned hardware tasks and join
        let mut hw_prc = Vec::new();
        let log_sender = log_s.clone();
        hw_prc.push(tokio::spawn(async move {
            prc_wait_on_event(1, "eventA", log_sender).await;
        }));
        let log_sender = log_s.clone();
        hw_prc.push(tokio::spawn(async move {
            prc_wait_on_event(2, "eventB", log_sender).await;
        }));
        trigger_events("eventA", 7, 10).await;
        trigger_events("eventB", 6, 6).await;

        // Register added hw_process as inflight
        for _i in 0..hw_prc.len() {
            scheduler::SchedulerAPI::register_new_prc();
        }
        sched.simulate(400).await;

        // Read order and check it
        let mut prc_log = Vec::new();
        while let Ok((tid, tick)) = log_r.try_recv() {
            prc_log.push((tid, tick));
        }
        assert_eq!(
            prc_log,
            vec![
                (2, 6),
                (1, 7),
                (2, 12),
                (1, 14),
                (2, 18),
                (1, 21),
                (2, 24),
                (1, 28),
                (2, 30),
                (1, 35),
                (2, 36),
                (1, 42),
                (1, 49),
                (1, 56),
                (1, 63),
                (1, 70)
            ]
        );
    }
}
